<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    کار با آرایه (۱)
</font>
</h1>

In [1]:
import numpy as np
np.random.seed(1400)

In [2]:
a = np.array([0, 1, 2, 3])
print(a)
print('a[0] =', a[0])
print('a[2] =', a[2])
print('a[-1] =', a[-1])

[0 1 2 3]
a[0] = 0
a[2] = 2
a[-1] = 3


In [3]:
a = np.random.randint(0, 10, (3, 5))
print(a)
print('a[2, 3] =', a[2, 3])

[[5 1 7 8 5]
 [8 1 8 3 8]
 [9 8 4 1 4]]
a[2, 3] = 1


In [4]:
a[2, 3] = 10
print('a[2, 3] =', a[2, 3])

a[2, 3] = 10


In [5]:
a[2, 3] = 3.14
print('a[2, 3] =', a[2, 3])

a[2, 3] = 3


In [6]:
a = np.array([0, 1, 2, 3, 4])
print(a[:3])
print(a[2:4])
print(a[1:5:2])
print(a[::-1])

[0 1 2]
[2 3]
[1 3]
[4 3 2 1 0]


In [7]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]])
print(a[:2, 1:])
print(a[1:3, ::2])

[[1 2]
 [4 5]]
[[3 5]
 [6 8]]


In [8]:
print(a[:2, 1])
print(a[2, :])
print(a[:, 1])
print(a[2])

[1 4]
[6 7 8]
[ 1  4  7 10]
[6 7 8]


In [9]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_a = a[1:3, 1:]
sub_a[0, 0] = 10
print(a)

[[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


In [10]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_copy_a = a[2:4, 1:].copy()
sub_copy_a[0, 0] = 10
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
a = np.arange(16)
print(a)
print(a.reshape(4, 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [12]:
a = np.array([1, 2, 3])
print(a.reshape(3, 1))
print(a.reshape(1, 3))

[[1]
 [2]
 [3]]
[[1 2 3]]


In [13]:
a = np.arange(12)
print(a.reshape(2, -1, 3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [14]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(a.reshape(-1))

[0 1 2 3 4 5 6 7 8]
