<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    توابع عمومی
</font>
</h1>

In [1]:
import numpy as np
np.random.seed(1400)

In [2]:
a = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9 
b = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9 
print('a =', a)
print('b =', b)

def cal_sum(a,b) :
    output = np.empty(len(a), dtype='int_')
    for i in range(len(a)):
        output[i] = a[i] + b[i]
    return output

print(cal_sum(a, b))

a = [5 1 7 8]
b = [5 8 1 8]
[10  9  8 16]


In [3]:
big_size = 10*1000*1000
a = np.random.randint(0, 10, big_size) 
b = np.random.randint(0, 10, big_size) 
%timeit cal_sum(a, b)

5.25 s ± 164 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit np.add(a, b) 

71.8 ms ± 22.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
a = np.random.randint(0, 10, 4) 
b = np.random.randint(0, 10, 4) 
print(np.add(a, b)) # قالب قبلی
print(a + b) # استفاده از عملگر معادل

[9 5 9 8]
[9 5 9 8]


In [6]:
a = np.array([0, 1, 2, 3])
b = np.array([-2, 10, 1, 5])
print('a + b =', np.add(a, b)) 
print('a + b =', a + b) # است a + b معادل np.add(a, b)

a + b = [-2 11  3  8]
a + b = [-2 11  3  8]


In [7]:
print('a - b =', np.subtract(a, b)) 
print('a - b =', a - b) # است a - b معادل np.subtract(a, b)

a - b = [ 2 -9  1 -2]
a - b = [ 2 -9  1 -2]


In [8]:
print('a * b =', np.multiply(a, b)) 
print('a * b =', a * b) # است a * b معادل np.multiply(a, b)

a * b = [ 0 10  2 15]
a * b = [ 0 10  2 15]


In [9]:
print('a / b =', np.divide(a, b)) 
print('a / b =', a / b) # است a / b معادل np.divide(a, b)

a / b = [-0.   0.1  2.   0.6]
a / b = [-0.   0.1  2.   0.6]


In [10]:
a = np.random.randint(0, 11, 5) # آرایه‌ای شامل 5 عدد تصادفی در بازه 0 تا 10
b = np.random.randint(-10, 11, 5) # آرایه‌ای شامل 5 عدد تصادفی در بازه 10- تا 10
print('a =', a)
print('b =', b)

a = [4 8 3 6 6]
b = [-8  6 -7  6  1]


In [11]:
print('absolute values of b =', np.abs(b)) 

absolute values of b = [8 6 7 6 1]


In [12]:
print('square values of a =', np.square(a) ) 

square values of a = [16 64  9 36 36]


In [13]:
np.seterr(invalid="ignore") # خطای ناشی از عملیات غیرمجاز را نادیده می‌گیرد
a = np.array([1 , 2 , -3 , 4, -5])
print('a = ', a)
print('isnan results for a =', np.isnan(a))
print('sqrt(a) = ', np.sqrt(a))
print('isnan resultes for sqrt(a) =', np.isnan(np.sqrt(a)))

a =  [ 1  2 -3  4 -5]
isnan results for a = [False False False False False]
sqrt(a) =  [1.         1.41421356        nan 2.                nan]
isnan resultes for sqrt(a) = [False False  True False  True]
